#!/usr/bin/env python3
"""
Generate build.ninja from all data/*.json (or labels.jsonl).
"""
import json, os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
TEMPLATES = ROOT / "templates"
BUILD = ROOT / "build"
NINJA = ROOT / "build.ninja"

def load_records():
    recs = []
    lj = DATA / "labels.jsonl"
    if lj.exists():
        for line in lj.read_text(encoding="utf-8").splitlines():
            line=line.strip()
            if not line:
                continue
            recs.append(json.loads(line))
    else:
        for p in sorted(DATA.glob("*.json")):
            recs.append(json.loads(p.read_text(encoding="utf-8")))
    return recs

recs = load_records()

header = """# Auto-generated by scripts/make_ninja.py
jinja2 = jinja2
latexmk = latexmk
latex_flags = -pdf -interaction=nonstopmode -halt-on-error -file-line-error

rule render
  command = $jinja2 templates/$template $json > $out
  description = RENDER templates/$template + $json -> $out

rule pdf
  command = $latexmk $latex_flags -jobname=$outbase $in
  description = PDF $in -> build/$outbase.pdf

"""

lines = [header]
all_targets = []

for rec in recs:
    t = rec["template_id"]
    doc = rec["doc_id"]
    tex_out = f"build/{t}/{doc}.tex"
    pdf_out = f"build/{t}/{doc}.pdf"
    outbase = f"build/{t}/{doc}"
    json_path = f"data/{doc}.json" if (DATA / f"{doc}.json").exists() else "data/labels.jsonl"
    template_file = f"{t}.tex.j2"
    lines.append(f"build {tex_out}: render | templates/{template_file} {json_path}")
    lines.append(f"  template = {template_file}")
    lines.append(f"  json = {json_path}\n")
    lines.append(f"build {pdf_out}: pdf {tex_out}")
    lines.append(f"  outbase = {outbase}\n")
    all_targets.append(pdf_out)

if not all_targets:
    all_targets = ["# (no targets)"]

lines.append("build all: phony " + " ".join(all_targets) + "\n")
lines.append("default all\n")

NINJA.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {NINJA}")
